package com.example.user.service;

import com.example.user.grpc.HelloWorldProto;
import com.example.user.models.User;
import com.example.user.repo.UserRepository;
import io.grpc.stub.StreamObserver;
import net.devh.boot.grpc.server.service.GrpcService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Sort;

@GrpcService
public class HelloWorldService extends com.example.user.grpc.GreeterGrpc.GreeterImplBase {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @Override
    public void sayHello(HelloWorldProto.HelloRequest request, StreamObserver<HelloWorldProto.HelloReply> responseObserver) {

        User n = new User();
        n.setName(request.getName());
        n.setEmail("email");
        userRepository.save(n);

        Iterable<User> allUsers = userRepository.findAll();

        for (User user: allUsers) {
            System.out.println(user.getName());
        }


        String responseMessage = "Hello, dear " + request.getName();
        HelloWorldProto.HelloReply reply = HelloWorldProto.HelloReply.newBuilder()
                .setMessage(responseMessage)
                .build();
        responseObserver.onNext(reply);
        responseObserver.onCompleted();
    }
}
