services:
  user_service:
    build:
      context: ./user_service
    ports:
      - "9090:9090"
    container_name: userService
    restart: always
  main_client_service:
    build:
      context: ./main_client_service
    ports:
      - "8080:8080"
    container_name: main_client_service
    restart: always