version: '3.8'
services:
  # Контейнер с базой данных пользователей
  user_db:
    image: mysql:latest
    # Показываю наружу порт
    ports:
      - "3306:3306"
    # Задаю параметры для инициализации БД
    environment:
      # Пароль к БД
      MYSQL_ROOT_PASSWORD: root
      # БД по умолчанию
      MYSQL_DATABASE: user_db
    # Линкую внешнюю папку для хранения БД
    volumes:
      - "./user_db:/var/lib/mysql"
    container_name: userDb
  user_service:
    build:
      context: ./user_service
    ports:
      - "9090:9090"
    container_name: userService
    restart: always
    depends_on:
      - user_db
  main_client_service:
    build:
      context: ./main_client_service
    ports:
      - "8080:8080"
    container_name: main_client_service
    restart: always