services:
  # Контейнер с базой данных пользователей
  user_db:
    image: mysql:latest
    # Показываю наружу порт
    ports:
      - "3306:3306"
    # Задаю параметры для инициализации БД
    environment:
      # Пароль к БД
      MYSQL_DATABASE_HOST: userdb
      MYSQL_DATABASE_USER: user
      MYSQL_DATABASE_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE_PORT: 3306
      # БД по умолчанию
      MYSQL_DATABASE: user_db
    # Линкую внешнюю папку для хранения БД
    volumes:
      - "./user_db:/var/lib/mysql"
    container_name: userdb
  user_service:
    build:
      context: ./user_service
    ports:
      - "9090:9090"
    container_name: userService
    restart: always
    depends_on:
      - user_db
    environment:
      - DATABASE_HOST=userdb
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=user_db
      - DATABASE_PORT=3306
  main_client_service:
    build:
      context: ./main_client_service
    ports:
      - "8080:8080"
    container_name: main_client_service
    restart: always