version: '3.1'

services:
  user_service:
    links:
      - db
    build:
      context: ./user_service
    ports:
      - "9090:9090"
    container_name: 'userService'
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
#    entrypoint: ["./wait-for-it.sh", "-s" ,"-t", "100", "db:3306", "--"]
#    command: ["echo", "!!!!!!!! Container_A is available now !!!!!!!!"]
  main_client_service:
    build:
      context: ./main_client_service
    ports:
      - "8080:8080"
    container_name: 'main_client_service'
    depends_on:
      - db
    restart: unless-stopped
  db:
    container_name: 'db'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro