version: '3.8'
services:
  user_service:
    build:
      context: ./user_service
    ports:
      - "81:81"
    depends_on:
      user_db:
        condition: service_healthy
  course_service:
    build:
      context: ./course_service
    ports:
      - "82:82"
  main_service:
    build:
      context: ./main_service
    ports:
      - "80:80"
  # Контейнер с базой данных пользователей
  user_db:
    image: mysql:latest
    # Подключаю к общей сети с другими контейнерами
    networks:
      - default
    # Показываю наружу порт
    ports:
      - "3306:3306"
    # Задаю параметры для инициализации БД
    environment:
      # Пароль к БД
      MYSQL_ROOT_PASSWORD: root
      # БД по умолчанию
      MYSQL_DATABASE: user_db
    # Линкую внешнюю папку для хранения БД
    volumes:
      - "./user_db:/var/lib/mysql"
    container_name: user_db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 1s
      retries: 1