version: '3.8'
services:
  user_service:
    build:
      context: ./user_service
    ports:
      - "9090:9090"
  main_client_service:
    build:
      context: ./main_client_service
    ports:
      - "8080:8080"