spring:
  datasource:
    url: jdbc:mysql://db:3306/mydatabase
    username: myuser
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
  liquibase:
    enabled: true
  application:
    name: api_user
  sql:
    init:
      mode: always